### ISSUE TITLE
thumbnails and branding logo not showing!

### ISSUE THREAD

**Issue by kliko22** [ignacionelson/ProjectSend#420]
I installed ProjectSend r885 on Ubuntu 14.04.5 server. And everything is working fine but the thumbnails and branding logo's doesn't show. I had the same issues whit Projectsend r754.

When I look in the source-file I see this with the branding logo 
`<img src="http://192.168.0.75/projectsend/includes/timthumb/timthumb.php?src=http://192.168.0.75/projectsend//img/custom/logo/logo.png&amp;w=300" alt="I_KB cloud" />`

I think the problem is the double "/" between the root folder and the img folder.

This is the same with the thumbnails 
`<img src="http://192.168.0.75/projectsend/includes/timthumb/timthumb.php?src=http://192.168.0.75/projectsend//upload/files/1497970118-d033e22ae348aeb5660fc2140aec35850c4da997-img_0526.jpg&amp;w=250&amp;q=90" alt="img 0526" />`

Does anyone have a solution for this?

Kind regards

**Comment by Syedwaheed** [comment]
I have the same problem but couldn't solve it yet.

**Comment by ignacionelson** [comment]
Hello! I've just fixed it, thanks for letting me know!
It's uploaded to the repository
<https://github.com/ignacionelson/ProjectSend/commit/c2c2f970348e5ae54dcdc58cd1efab7251478fcf>,
but if you want to make the change yourself, open the file sys.vars.php and
change line  186 from
define('UPLOADED_FILES_URL', '/upload/files/');
to
define('UPLOADED_FILES_URL', 'upload/files/');

Let me know if that worked for you!

Also, please note that downloading from the repo directly is unadvised as
there are some features that are still not finished. In this case the one
that might give you trouble is, if you allow clients to register for
themselves, you will see the requests on the new Clients -> Account
requests page, but you won't be able to accept or deny them yet.
I believe that this will be finished by the weekend.

Regards,
Ignacio


*IGNACIO NELSON*
WordPress specialist
Buenos Aires, Argentina

*Mobile:* (54) 11 31 52 59 31
http://about.me/ignacionelson <http://subwaydesign.com.ar>

2017-06-21 4:03 GMT-03:00 kliko22 <notifications@github.com>:

**Comment by kliko22** [comment]
Hello! Thanks for the quick reaction and the good work 

I just changes the line, but the thumbs doesn't show up. The link to the source file is changed, but no thumb. When I copy and paste the src-link I see that the image works but the thumb doesn't show. Maybe there is a problem with timthumb?

And the problem with the branding logo isn't solved with this. The logo works on the login page, but not on the clientpage at the left with the default template and on the top with the PinBoxes template.

And I know that this is a developer version but I had the same problems with the r754 version!

**Comment by remez** [comment]
Please, try checking "Use file's absolute path" in Options -> Thumbnails page. 
This solved the problem for me.

**Comment by kliko22** [comment]
Thank you for your reaction, but I already tried it so you can see in the source-file link in my first message

**Comment by remez** [comment]
Do you see your logo in preview?  (Option -> Branding).
Check if the owner and permission of the files and directories of your projectsend installation are correct.

**Comment by kliko22** [comment]
I see the logo in the preview and als in the login page. And the permissions are set on www-data

**Comment by Syedwaheed** [comment]
I can't see the preview of the logo in (Option-> Branding). Where would i change permission of the files and directories? @remez

**Comment by remez** [comment]
First thing try this:
try checking "Use file's absolute path" in Options -> Thumbnails page.
Clear the cache of your browser

I think that permissons varies depending of the installation.

In my CentOS 7, via ssh, i I go under the directory where projectsend i  installed, then

```
chown  -R  apache:apache  `find  .`
chmod  -R  740  `find  .`
```

**Comment by ignacionelson** [comment]
Here's a little dirty secret (don't tell anyone! haha)
The log in form and the options page do not use timthumb to show the file, so it's not processed by it, just rescaled via CSS.
That is why you might see it there and not on the clients file lists.

I urgently need to replace timthumb with something better, probably a way to create the thumbnails immediately after uploading the files and not calling them through a separate process each time they are needed.

Timthumb was a great help when adding thumbnails to PS, but a more custom solution needs to be applied now. I'm looking for one, but I haven't decided for anything yet :/

**Comment by kliko22** [comment]
Thanks for the dirty secret (haha)

Can't you just remove the line of TimThumb and add the css inline?

**Comment by wsjake** [comment]
Make sure you have the PHP GD Library is installed and enabled. That was my fix.

**Comment by kliko22** [comment]
Hello wsjake,

I checked it and installed it, but no change for me

**Comment by olimax** [comment]
includes/functions.php line:909
`   if (file_exists(ROOT_DIR.$branding['filename'])) {`
should be:
`    if (file_exists(ROOT_DIR  . "/"/ . $branding['filename'])) {`

**Comment by ignacionelson** [comment]
Thanks @olimax 
I've applied your solution on 931ee9a
Looks like everything is working now!

**Comment by Syedwaheed** [comment]
Thanks @olimax .
I was adding line "/" in $branding variable just like "$branding['filename'] = '/img/projectsend-logo.png';" but couldn't work out. Your solution is perfect to it.

**Comment by kliko22** [comment]
Thanks @olimax 
It's now working like it should be.

**Comment by kliko22** [comment]
@ignacionelson 
I think this problem is solved!

**Comment by hubthomas** [comment]
Hi, I'm reopen this issue... 

The logo shows up in the login admin page when I activate 'Use File's absolute Path", but not in the thumbnails. In the console I have this message "Failed to load resource: the server responded with a status of 400 (Bad Request)" for timthumb.php 

I asked my Host provider if they could help me in this is what they sent me ? 

'I can see you are having an "open_basedir restriction" 

[Mon Feb 19 15:56:53.722510 2018] [warn] [pid 16557] fcgid_bucket.c(153):
[client 188.118.33.125:50243] mod_fcgid: stderr: PHP Warning:  file_exists() [
function.file-exists ]: open_basedir restriction in effect.
File(/data/sites/web/louisdepoorterebe/www/agent/includes/timthumb/timthumb.php/:
443/agent//img/custom/logo/ldplogo_vect_black_since1929.png) is not within the
allowed path(s):
(/data/sites/web/louisdepoorterebe:/usr/local/php-5.3/lib/php:/usr/bin:/tmp:/data
/vendor-scripts:/data/sites/web/disabled) in
/data/sites/web/louisdepoorterebe/www/agent/includes/timthumb/timthumb.php on
line 901
[Mon Feb 19 15:57:00.795896 2018] [warn] [pid 16557] fcgid_bucket.c(153):
[client 188.118.33.125:50247] mod_fcgid: stderr: PHP Warning:  file_exists() [
function.file-exists ]: open_basedir restriction in effect.File(/data/sites/web/louisdepoorterebe/www/agent/includes/timthumb/timthumb.php/:
443/agent//img/custom/logo/ldplogo_vect_black_since1929.png) is not within the
allowed path(s):
(/data/sites/web/louisdepoorterebe:/usr/local/php-5.3/lib/php:/usr/bin:/tmp:/data
/vendor-scripts:/data/sites/web/disabled) in
/data/sites/web/louisdepoorterebe/www/agent/includes/timthumb/timthumb.php on
line 901

- theses are the allowed paths:

/data/sites/web/louisdepoorterebe:/usr/local/php-5.3/lib/php:/usr/bin:/tmp:/data/
vendor-scripts:/data/sites/web/disabled

I tried to fix this on my own but I have tested so many things... I don't know what to do. ? 
I am using the r754 version. May I upload the newer version of timthumb.php ?


Thanks for help
